export const papeis = [
  // { papel: "ABRE3", inativo: true },
  // { papel: "AEDU1", inativo: true },
  // { papel: "AGEN3", inativo: true },
  // { papel: "ALLL1", inativo: true },
  // { papel: "ALUP1", inativo: true },
  // { papel: "AORE3", inativo: true },
  // { papel: "BAHI1", inativo: true },
  // { papel: "BBTG1", inativo: true },
  // { papel: "BPAC1", inativo: true },
  // { papel: "BPAT3", inativo: true },
  // { papel: "BPNM4", inativo: true },
  // { papel: "BRGE1", inativo: true },
  // { papel: "BVMF3", inativo: true },
  // { papel: "CZLT3", inativo: true },
  // { papel: "DAGB3", inativo: true },
  // { papel: "DUFB1", inativo: true },
  // { papel: "ENGI1", inativo: true },
  // { papel: "ESTC1", inativo: true },
  // { papel: "GBIO3", inativo: true },
  // { papel: "GPIV3", inativo: true },
  // { papel: "HRTP3", inativo: true },
  // { papel: "IDVL1", inativo: true },
  // { papel: "INET3", inativo: true },
  // { papel: "KLBN1", inativo: true },
  // { papel: "KROT1", inativo: true },
  // { papel: "LATM1", inativo: true },
  // { papel: "MILK3", inativo: true },
  // { papel: "MLFT3", inativo: true },
  // { papel: "MLPA1", inativo: true },
  // { papel: "PALF1", inativo: true },
  // { papel: "PARC3", inativo: true },
  // { papel: "QGEP3", inativo: true },
  // { papel: "RCTB3", inativo: true },
  // { papel: "RCTB4", inativo: true },
  // { papel: "RNEW1", inativo: true },
  // { papel: "RNAR3", inativo: true },
  // { papel: "SAPR1", inativo: true },
  // { papel: "RUMO3", inativo: true },
  // { papel: "SANB1", inativo: true },
  // { papel: "SEBB1", inativo: true },
  // { papel: "SGAS4", inativo: true },
  // { papel: "SGAS3", inativo: true },
  // { papel: "SNSL3", inativo: true },
  // { papel: "STBP1", inativo: true },
  // { papel: "SULA1", inativo: true },
  // { papel: "STLB3", inativo: true },
  // { papel: "SWET3", inativo: true },
  // { papel: "TAEE1", inativo: true },
  // { papel: "TARP1", inativo: true },
  // { papel: "TBLE3", inativo: true },
  // { papel: "TEFC1", inativo: true },
  // { papel: "TIBR3", inativo: true },
  // { papel: "TIBR5", inativo: true },
  // { papel: "TIBR6", inativo: true },
  // { papel: "TIET1", inativo: true },
  // { papel: "TMGC1", inativo: true },
  // { papel: "UBBR1", inativo: true },
  // { papel: "VAGR3", inativo: true },
  // { papel: "VVAR1", inativo: true },
  // { papel: "WSON3", inativo: true },
  // { papel: "BBTG1", inativo: true },
  // { papel: "BRGE1", inativo: true },
  // { papel: "BBTG1", inativo: true },
  // { papel: "RCTB3", inativo: true },
  // { papel: "TMGC1", inativo: true },
  // { papel: "TMGC1", inativo: true },
  // { papel: "RCTB4", inativo: true },
  { papel: "CASN3", setor: "Água e Saneamento", subsetor: "Água e Saneamento" },
  { papel: "CSMG3", setor: "Água e Saneamento", subsetor: "Água e Saneamento" },
  { papel: "SAPR3", setor: "Água e Saneamento", subsetor: "Água e Saneamento" },
  { papel: "SBSP3", setor: "Água e Saneamento", subsetor: "Água e Saneamento" },
  { papel: "SAPR4", setor: "Água e Saneamento", subsetor: "Água e Saneamento" },
  { papel: "CVCB3", setor: "Viagens e Lazer", subsetor: "Viagens e Turismo" },
  {papel: "HGTX3",setor: "Tecidos. Vestuário e Calçados",subsetor: "Vestuário" },
//   {papel: "HGTX4",setor: "Tecidos. Vestuário e Calçados",subsetor: "Vestuário" ,inativo: true},
//   {papel: "MRSL3",setor: "Tecidos. Vestuário e Calçados",subsetor: "Vestuário" ,inativo: true},
//   {papel: "MRSL4",setor: "Tecidos. Vestuário e Calçados",subsetor: "Vestuário" ,inativo: true},
//   {papel: "STRP4",setor: "Tecidos. Vestuário e Calçados",subsetor: "Vestuário" ,inativo: true},
//   {papel: "GAZO3",setor: "Utilidades Domésticas",subsetor: "Utensílios Domésticos" ,inativo: true},
//   {papel: "GAZO4",setor: "Utilidades Domésticas",subsetor: "Utensílios Domésticos" ,inativo: true},
//   {papel: "HETA3",setor: "Utilidades Domésticas",subsetor: "Utensílios Domésticos" ,inativo: true},
  {papel: "HETA4",setor: "Utilidades Domésticas",subsetor: "Utensílios Domésticos" },
  {papel: "NAFG3",setor: "Utilidades Domésticas",subsetor: "Utensílios Domésticos" },
  {papel: "NAFG4",setor: "Utilidades Domésticas",subsetor: "Utensílios Domésticos" },
  { papel: "JSLG3", setor: "Transporte", subsetor: "Transporte Rodoviário" },
  { papel: "TGMA3", setor: "Transporte", subsetor: "Transporte Rodoviário" },
  { papel: "LOGN3", setor: "Transporte", subsetor: "Transporte Hidroviário" },
//   { papel: "LUXM3", setor: "Transporte", subsetor: "Transporte Hidroviário" ,inativo: true},
  { papel: "LUXM4", setor: "Transporte", subsetor: "Transporte Hidroviário" },
//   { papel: "ALLL4", setor: "Transporte", subsetor: "Transporte Ferroviário" ,inativo: true},
//   { papel: "ALLL3", setor: "Transporte", subsetor: "Transporte Ferroviário" ,inativo: true},
  { papel: "RAIL3", setor: "Transporte", subsetor: "Transporte Ferroviário" },
  { papel: "RLOG3", setor: "Transporte", subsetor: "Transporte Ferroviário" },
  { papel: "AZUL4", setor: "Transporte", subsetor: "Transporte Aéreo" },
  { papel: "GOLL4", setor: "Transporte", subsetor: "Transporte Aéreo" },
//   { papel: "TAMM3", setor: "Transporte", subsetor: "Transporte Aéreo" ,inativo: true},
//   { papel: "TAMM4", setor: "Transporte", subsetor: "Transporte Aéreo" ,inativo: true},
//   { papel: "TANC4", setor: "Transporte", subsetor: "Transporte Aéreo" ,inativo: true},
//   { papel: "VAGV3", setor: "Transporte", subsetor: "Transporte Aéreo" ,inativo: true},
//   { papel: "VAGV4", setor: "Transporte", subsetor: "Transporte Aéreo" ,inativo: true},
//   { papel: "VPTA3", setor: "Transporte", subsetor: "Transporte Aéreo" ,inativo: true},
//   { papel: "VPTA4", setor: "Transporte", subsetor: "Transporte Aéreo" ,inativo: true},
//   { papel: "NETC3", setor: "Mídia", subsetor: "Televisão por Assinatura" ,inativo: true},
//   { papel: "NETC4", setor: "Mídia", subsetor: "Televisão por Assinatura" ,inativo: true},
//   { papel: "PLIM4", setor: "Mídia", subsetor: "Televisão por Assinatura" ,inativo: true},
//   { papel: "TCSL4", setor: "Telefonia Móvel", subsetor: "Telefonia Móvel" ,inativo: true},
  { papel: "TIMP3", setor: "Telefonia Móvel", subsetor: "Telefonia Móvel" },
//   { papel: "TMCP3", setor: "Telefonia Móvel", subsetor: "Telefonia Móvel" ,inativo: true},
//   { papel: "TMCP4", setor: "Telefonia Móvel", subsetor: "Telefonia Móvel" ,inativo: true},
//   { papel: "TMGC3", setor: "Telefonia Móvel", subsetor: "Telefonia Móvel" ,inativo: true},
//   { papel: "TMGC7", setor: "Telefonia Móvel", subsetor: "Telefonia Móvel" ,inativo: true},
//   { papel: "TNCP3", setor: "Telefonia Móvel", subsetor: "Telefonia Móvel" ,inativo: true},
//   { papel: "TNCP4", setor: "Telefonia Móvel", subsetor: "Telefonia Móvel" ,inativo: true},
//   { papel: "TPRC3", setor: "Telefonia Móvel", subsetor: "Telefonia Móvel" ,inativo: true},
//   { papel: "TPRC6", setor: "Telefonia Móvel", subsetor: "Telefonia Móvel" ,inativo: true},
//   { papel: "TSPP3", setor: "Telefonia Móvel", subsetor: "Telefonia Móvel" ,inativo: true},
//   { papel: "TSPP4", setor: "Telefonia Móvel", subsetor: "Telefonia Móvel" ,inativo: true},
//   { papel: "VIVO3", setor: "Telefonia Móvel", subsetor: "Telefonia Móvel" ,inativo: true},
//   { papel: "VIVO4", setor: "Telefonia Móvel", subsetor: "Telefonia Móvel" ,inativo: true},
//   { papel: "BRTP3", setor: "Telefonia Fixa", subsetor: "Telefonia Fixa" ,inativo: true},
//   { papel: "BRTP4", setor: "Telefonia Fixa", subsetor: "Telefonia Fixa" ,inativo: true},
//   { papel: "EBTP3", setor: "Telefonia Fixa", subsetor: "Telefonia Fixa" ,inativo: true},
//   { papel: "EBTP4", setor: "Telefonia Fixa", subsetor: "Telefonia Fixa" ,inativo: true},
//   { papel: "GVTT3", setor: "Telefonia Fixa", subsetor: "Telefonia Fixa" ,inativo: true},
  { papel: "JPSA3", setor: "Telefonia Fixa", subsetor: "Telefonia Fixa" },
//   { papel: "LFFE3", setor: "Telefonia Fixa", subsetor: "Telefonia Fixa" ,inativo: true},
//   { papel: "LFFE4", setor: "Telefonia Fixa", subsetor: "Telefonia Fixa" ,inativo: true},
  { papel: "MLFT4", setor: "Telefonia Fixa", subsetor: "Telefonia Fixa" },
  { papel: "OIBR3", setor: "Telefonia Fixa", subsetor: "Telefonia Fixa" },
  { papel: "OIBR4", setor: "Telefonia Fixa", subsetor: "Telefonia Fixa" },
//   { papel: "PITI4", setor: "Telefonia Fixa", subsetor: "Telefonia Fixa" ,inativo: true},
//   { papel: "TMAR3", setor: "Telefonia Fixa", subsetor: "Telefonia Fixa" ,inativo: true},
//   { papel: "TMAR5", setor: "Telefonia Fixa", subsetor: "Telefonia Fixa" ,inativo: true},
//   { papel: "TMAR6", setor: "Telefonia Fixa", subsetor: "Telefonia Fixa" ,inativo: true},
//   { papel: "TNLP3", setor: "Telefonia Fixa", subsetor: "Telefonia Fixa" ,inativo: true},
//   { papel: "TNLP4", setor: "Telefonia Fixa", subsetor: "Telefonia Fixa" ,inativo: true},
  { papel: "VIVT3", setor: "Telefonia Fixa", subsetor: "Telefonia Fixa" },
  { papel: "VIVT4", setor: "Telefonia Fixa", subsetor: "Telefonia Fixa" },
  {papel: "AMAR3",setor: "Comércio",subsetor: "Tecidos. Vestuário e Calçados" },
  {papel: "ARZZ3",setor: "Comércio",subsetor: "Tecidos. Vestuário e Calçados" },
  {papel: "CGRA3",setor: "Comércio",subsetor: "Tecidos. Vestuário e Calçados" },
  {papel: "CGRA4",setor: "Comércio",subsetor: "Tecidos. Vestuário e Calçados" },
  {papel: "CNTO3",setor: "Comércio",subsetor: "Tecidos. Vestuário e Calçados" },
  {papel: "GUAR3",setor: "Comércio",subsetor: "Tecidos. Vestuário e Calçados" },
  {papel: "GUAR4",setor: "Comércio",subsetor: "Tecidos. Vestuário e Calçados" },
  {papel: "LLIS3",setor: "Comércio",subsetor: "Tecidos. Vestuário e Calçados" },
  {papel: "LREN3",setor: "Comércio",subsetor: "Tecidos. Vestuário e Calçados" },
//   {papel: "LREN4",setor: "Comércio",subsetor: "Tecidos. Vestuário e Calçados" ,inativo: true},
//   {papel: "MARI3",setor: "Comércio",subsetor: "Tecidos. Vestuário e Calçados" ,inativo: true},
  {papel: "CRIV3",setor: "Financeiros",subsetor: "Soc Crédito e Financiamento" },
  {papel: "CRIV4",setor: "Financeiros",subsetor: "Soc Crédito e Financiamento" },
  {papel: "MERC3",setor: "Financeiros",subsetor: "Soc Crédito e Financiamento" },
  {papel: "MERC4",setor: "Financeiros",subsetor: "Soc Crédito e Financiamento" },
//   { papel: "ACES4", setor: "Siderurgia e Metalurgia", subsetor: "Siderurgia" ,inativo: true},
//   { papel: "ACES3", setor: "Siderurgia e Metalurgia", subsetor: "Siderurgia" ,inativo: true},
//   { papel: "AVIL3", setor: "Siderurgia e Metalurgia", subsetor: "Siderurgia" ,inativo: true},
  { papel: "CSNA3", setor: "Siderurgia e Metalurgia", subsetor: "Siderurgia" },
  { papel: "FESA3", setor: "Siderurgia e Metalurgia", subsetor: "Siderurgia" },
  { papel: "FESA4", setor: "Siderurgia e Metalurgia", subsetor: "Siderurgia" },
  { papel: "GGBR3", setor: "Siderurgia e Metalurgia", subsetor: "Siderurgia" },
  { papel: "GGBR4", setor: "Siderurgia e Metalurgia", subsetor: "Siderurgia" },
  { papel: "GOAU3", setor: "Siderurgia e Metalurgia", subsetor: "Siderurgia" },
  { papel: "GOAU4", setor: "Siderurgia e Metalurgia", subsetor: "Siderurgia" },
  { papel: "USIM3", setor: "Siderurgia e Metalurgia", subsetor: "Siderurgia" },
  { papel: "USIM5", setor: "Siderurgia e Metalurgia", subsetor: "Siderurgia" },
  { papel: "USIM6", setor: "Siderurgia e Metalurgia", subsetor: "Siderurgia" },
//   {papel: "IMBI3",setor: "Transporte",subsetor: "Serviços de Apoio e Armazenagem" ,inativo: true},
//   {papel: "IMBI4",setor: "Transporte",subsetor: "Serviços de Apoio e Armazenagem" ,inativo: true},
//   {papel: "PRML3",setor: "Transporte",subsetor: "Serviços de Apoio e Armazenagem" ,inativo: true},
//   {papel: "PRTX3",setor: "Transporte",subsetor: "Serviços de Apoio e Armazenagem" ,inativo: true},
  {papel: "STBP3",setor: "Transporte",subsetor: "Serviços de Apoio e Armazenagem" },
//   {papel: "VPSC3",setor: "Transporte",subsetor: "Serviços de Apoio e Armazenagem" ,inativo: true},
//   {papel: "VPSC4",setor: "Transporte",subsetor: "Serviços de Apoio e Armazenagem" ,inativo: true},
  {papel: "AALR3",setor: "Saúde",subsetor: "Serviços Médico - Hospitalares. Análises e Diagnósticos" },
//   {papel: "AMIL3",setor: "Saúde",subsetor: "Serviços Médico - Hospitalares. Análises e Diagnósticos" ,inativo: true},
  {papel: "DASA3",setor: "Saúde",subsetor: "Serviços Médico - Hospitalares. Análises e Diagnósticos" },
  {papel: "FLRY3",setor: "Saúde",subsetor: "Serviços Médico - Hospitalares. Análises e Diagnósticos" },
  {papel: "GNDI3",setor: "Saúde",subsetor: "Serviços Médico - Hospitalares. Análises e Diagnósticos" },
  {papel: "HAPV3",setor: "Saúde",subsetor: "Serviços Médico - Hospitalares. Análises e Diagnósticos" },
//   {papel: "MEDI3",setor: "Saúde",subsetor: "Serviços Médico - Hospitalares. Análises e Diagnósticos" ,inativo: true},
  {papel: "ODPV3",setor: "Saúde",subsetor: "Serviços Médico - Hospitalares. Análises e Diagnósticos" },
  {papel: "PARD3",setor: "Saúde",subsetor: "Serviços Médico - Hospitalares. Análises e Diagnósticos" },
  {papel: "QUAL3",setor: "Saúde",subsetor: "Serviços Médico - Hospitalares. Análises e Diagnósticos" },
//   {papel: "TEMP3",setor: "Saúde",subsetor: "Serviços Médico - Hospitalares. Análises e Diagnósticos" ,inativo: true},
//   {papel: "BMEF3",setor: "Serviços Financeiros Diversos",subsetor: "Serviços Financeiros Diversos" ,inativo: true},
//   {papel: "BOVH3",setor: "Serviços Financeiros Diversos",subsetor: "Serviços Financeiros Diversos" ,inativo: true},
  {papel: "CIEL3",setor: "Serviços Financeiros Diversos",subsetor: "Serviços Financeiros Diversos" },
//   {papel: "CTIP3",setor: "Serviços Financeiros Diversos",subsetor: "Serviços Financeiros Diversos" ,inativo: true},
//   {papel: "RDCD3",setor: "Serviços Financeiros Diversos",subsetor: "Serviços Financeiros Diversos" ,inativo: true},
//   {papel: "VNET3",setor: "Serviços Financeiros Diversos",subsetor: "Serviços Financeiros Diversos" ,inativo: true},
  { papel: "CARD3", setor: "Serviços", subsetor: "Serviços Diversos" },
  { papel: "DTCY3", setor: "Serviços", subsetor: "Serviços Diversos" },
  { papel: "LIQO3", setor: "Serviços", subsetor: "Serviços Diversos" },
  { papel: "VLID3", setor: "Serviços", subsetor: "Serviços Diversos" },
  { papel: "BBSE3", setor: "Previdência e Seguros", subsetor: "Seguradoras" },
  { papel: "CSAB3", setor: "Previdência e Seguros", subsetor: "Seguradoras" },
  { papel: "CSAB4", setor: "Previdência e Seguros", subsetor: "Seguradoras" },
  { papel: "IRBR3", setor: "Previdência e Seguros", subsetor: "Seguradoras" },
  { papel: "PEAB3", setor: "Previdência e Seguros", subsetor: "Seguradoras" },
  { papel: "PEAB4", setor: "Previdência e Seguros", subsetor: "Seguradoras" },
  { papel: "PSSA3", setor: "Previdência e Seguros", subsetor: "Seguradoras" },
//   { papel: "SASG3", setor: "Previdência e Seguros", subsetor: "Seguradoras" ,inativo: true},
  { papel: "SULA3", setor: "Previdência e Seguros", subsetor: "Seguradoras" },
  { papel: "SULA4", setor: "Previdência e Seguros", subsetor: "Seguradoras" },
  {papel: "BKBR3",setor: "Hoteis e Restaurantes",subsetor: "Restaurante e Similares" },
//   {papel: "IMCH3",setor: "Hoteis e Restaurantes",subsetor: "Restaurante e Similares" ,inativo: true},
  {papel: "MEAL3",setor: "Hoteis e Restaurantes",subsetor: "Restaurante e Similares" },
  { papel: "CRPG3", setor: "Químicos", subsetor: "Químicos Diversos" },
  { papel: "CRPG5", setor: "Químicos", subsetor: "Químicos Diversos" },
  { papel: "CRPG6", setor: "Químicos", subsetor: "Químicos Diversos" },
//   {papel: "DSUL3",setor: "Programas e Serviços",subsetor: "Programas e Serviços" ,inativo: true},
  {papel: "IDNT3",setor: "Programas e Serviços",subsetor: "Programas e Serviços" },
  {papel: "LINX3",setor: "Programas e Serviços",subsetor: "Programas e Serviços" },
  {papel: "SQIA3",setor: "Programas e Serviços",subsetor: "Programas e Serviços" },
  {papel: "TOTS3",setor: "Programas e Serviços",subsetor: "Programas e Serviços" },
//   {papel: "TVIT3",setor: "Programas e Serviços",subsetor: "Programas e Serviços" ,inativo: true},
//   {papel: "UOLL4",setor: "Programas e Serviços",subsetor: "Programas e Serviços" ,inativo: true},
  { papel: "MPLU3", setor: "Diversos", subsetor: "Programas de Fidelização" },
  { papel: "SMLS3", setor: "Diversos", subsetor: "Programas de Fidelização" },
//   { papel: "SMLE3", setor: "Diversos", subsetor: "Programas de Fidelização" ,inativo: true},
  {papel: "SHOW3",setor: "Viagens e Lazer",subsetor: "Produção de Eventos e Shows" },
  {papel: "ADHM3",setor: "Prods de Uso Pessoal e de Limpeza",subsetor: "Produtos de Uso Pessoal" },
  {papel: "NATU3",setor: "Prods de Uso Pessoal e de Limpeza",subsetor: "Produtos de Uso Pessoal" },
//   {papel: "VTLM3",setor: "Prods de Uso Pessoal e de Limpeza",subsetor: "Produtos de Uso Pessoal" ,inativo: true},
//   {papel: "BOBR3",setor: "Prods de Uso Pessoal e de Limpeza",subsetor: "Produtos de Limpeza" ,inativo: true},
  {papel: "BOBR4",setor: "Prods de Uso Pessoal e de Limpeza",subsetor: "Produtos de Limpeza" },
  { papel: "BTOW3", setor: "Comércio", subsetor: "Produtos Diversos" },
  { papel: "HYPE3", setor: "Comércio", subsetor: "Produtos Diversos" },
  { papel: "LAME3", setor: "Comércio", subsetor: "Produtos Diversos" },
  { papel: "LAME4", setor: "Comércio", subsetor: "Produtos Diversos" },
  { papel: "BRKM3", setor: "Químicos", subsetor: "Petroquímicos" },
  { papel: "BRKM5", setor: "Químicos", subsetor: "Petroquímicos" },
  { papel: "BRKM6", setor: "Químicos", subsetor: "Petroquímicos" },
  { papel: "ELEK3", setor: "Químicos", subsetor: "Petroquímicos" },
  { papel: "ELEK4", setor: "Químicos", subsetor: "Petroquímicos" },
  { papel: "GPCP3", setor: "Químicos", subsetor: "Petroquímicos" },
//   { papel: "PEFX5", setor: "Químicos", subsetor: "Petroquímicos" ,inativo: true},
//   { papel: "PEFX3", setor: "Químicos", subsetor: "Petroquímicos" ,inativo: true},
//   { papel: "PNOR5", setor: "Químicos", subsetor: "Petroquímicos" ,inativo: true},
//   { papel: "PNOR6", setor: "Químicos", subsetor: "Petroquímicos" ,inativo: true},
//   { papel: "PQUN3", setor: "Químicos", subsetor: "Petroquímicos" ,inativo: true},
//   { papel: "PQUN4", setor: "Químicos", subsetor: "Petroquímicos" ,inativo: true},
//   { papel: "RHDS4", setor: "Químicos", subsetor: "Petroquímicos" ,inativo: true},
//   { papel: "RHDS3", setor: "Químicos", subsetor: "Petroquímicos" ,inativo: true},
//   { papel: "SZPQ4", setor: "Químicos", subsetor: "Petroquímicos" ,inativo: true},
  { papel: "UNIP3", setor: "Químicos", subsetor: "Petroquímicos" },
  { papel: "UNIP5", setor: "Químicos", subsetor: "Petroquímicos" },
  { papel: "UNIP6", setor: "Químicos", subsetor: "Petroquímicos" },
//   { papel: "ARCZ3", setor: "Madeira e Papel", subsetor: "Papel e Celulose" ,inativo: true},
//   { papel: "ARCZ6", setor: "Madeira e Papel", subsetor: "Papel e Celulose" ,inativo: true},
  { papel: "FIBR3", setor: "Madeira e Papel", subsetor: "Papel e Celulose" },
  { papel: "KLBN4", setor: "Madeira e Papel", subsetor: "Papel e Celulose" },
  { papel: "KLBN3", setor: "Madeira e Papel", subsetor: "Papel e Celulose" },
//   { papel: "MLPA3", setor: "Madeira e Papel", subsetor: "Papel e Celulose" ,inativo: true},
//   { papel: "MLPA4", setor: "Madeira e Papel", subsetor: "Papel e Celulose" ,inativo: true},
  { papel: "MSPA3", setor: "Madeira e Papel", subsetor: "Papel e Celulose" },
  { papel: "MSPA4", setor: "Madeira e Papel", subsetor: "Papel e Celulose" },
  { papel: "RANI3", setor: "Madeira e Papel", subsetor: "Papel e Celulose" },
  { papel: "RANI4", setor: "Madeira e Papel", subsetor: "Papel e Celulose" },
//   { papel: "SUZB6", setor: "Madeira e Papel", subsetor: "Papel e Celulose" ,inativo: true},
//   { papel: "SUZB5", setor: "Madeira e Papel", subsetor: "Papel e Celulose" ,inativo: true},
  { papel: "SUZB3", setor: "Madeira e Papel", subsetor: "Papel e Celulose" },
//   { papel: "VCPA4", setor: "Madeira e Papel", subsetor: "Papel e Celulose" ,inativo: true},
//   {papel: "RJCP3",setor: "Financeiros",subsetor: "Outros Intermediários Financeiros" ,inativo: true},
  { papel: "ATOM3", setor: "Outros", subsetor: "Outros" },
//   { papel: "FIGE3", setor: "Outros", subsetor: "Outros" ,inativo: true},
//   { papel: "FIGE4", setor: "Outros", subsetor: "Outros" ,inativo: true},
  { papel: "MAPT3", setor: "Outros", subsetor: "Outros" },
  { papel: "MAPT4", setor: "Outros", subsetor: "Outros" },
  { papel: "TELB4", setor: "Outros", subsetor: "Outros" },
  { papel: "TELB3", setor: "Outros", subsetor: "Outros" },
  { papel: "UCAS3", setor: "Utilidades Domésticas", subsetor: "Móveis" },
  {papel: "OSXB3",setor: "Petróleo. Gás e Biocombustiveis",subsetor: "Máquinas e Equipamentos" },
//   {papel: "BDLL3",setor: "Máquinas e Equipamentos",subsetor: "Máqs e Equips Industriais" ,inativo: true},
  {papel: "BDLL4",setor: "Máquinas e Equipamentos",subsetor: "Máqs e Equips Industriais" },
  {papel: "INEP3",setor: "Máquinas e Equipamentos",subsetor: "Máqs e Equips Industriais" },
  {papel: "INEP4",setor: "Máquinas e Equipamentos",subsetor: "Máqs e Equips Industriais" },
  {papel: "KEPL3",setor: "Máquinas e Equipamentos",subsetor: "Máqs e Equips Industriais" },
  {papel: "NORD3",setor: "Máquinas e Equipamentos",subsetor: "Máqs e Equips Industriais" },
//   {papel: "ROMI4",setor: "Máquinas e Equipamentos",subsetor: "Máqs e Equips Industriais" ,inativo: true},
  {papel: "ROMI3",setor: "Máquinas e Equipamentos",subsetor: "Máqs e Equips Industriais" },
  {papel: "BALM3",setor: "Máquinas e Equipamentos",subsetor: "Máqs e Equips Hospitalares" },
  {papel: "BALM4",setor: "Máquinas e Equipamentos",subsetor: "Máqs e Equips Hospitalares" },
//   {papel: "CELM3",setor: "Máquinas e Equipamentos",subsetor: "Máqs e Equips Hospitalares" ,inativo: true},
  {papel: "EALT4",setor: "Máquinas e Equipamentos",subsetor: "Máqs e Equips Construção e Agrícolas" },
  {papel: "EALT3",setor: "Máquinas e Equipamentos",subsetor: "Máqs e Equips Construção e Agrícolas" },
  {papel: "MTSA4",setor: "Máquinas e Equipamentos",subsetor: "Máqs e Equips Construção e Agrícolas" },
  {papel: "LUPA3",setor: "Máquinas e Equipamentos",subsetor: "Motores. Compressores e Outros" },
  {papel: "SHUL4",setor: "Máquinas e Equipamentos",subsetor: "Motores. Compressores e Outros" },
  {papel: "WEGE3",setor: "Máquinas e Equipamentos",subsetor: "Motores. Compressores e Outros" },
//   {papel: "WEGE4",setor: "Máquinas e Equipamentos",subsetor: "Motores. Compressores e Outros" ,inativo: true},
  { papel: "CCXC3", setor: "Mineração", subsetor: "Minerais Metálicos" },
  { papel: "MMXM3", setor: "Mineração", subsetor: "Minerais Metálicos" },
//   { papel: "VALE5", setor: "Mineração", subsetor: "Minerais Metálicos" ,inativo: true},
  { papel: "VALE3", setor: "Mineração", subsetor: "Minerais Metálicos" },
  {papel: "BIOM3",setor: "Saúde",subsetor: "Medicamentos e Outros Produtos" },
//   {papel: "BIOM4",setor: "Saúde",subsetor: "Medicamentos e Outros Produtos" ,inativo: true},
  {papel: "CREM3",setor: "Saúde",subsetor: "Medicamentos e Outros Produtos" },
//   {papel: "CREM4",setor: "Saúde",subsetor: "Medicamentos e Outros Produtos" ,inativo: true},
  {papel: "OFSA3",setor: "Saúde",subsetor: "Medicamentos e Outros Produtos" },
  {papel: "BPHA3",setor: "ComércDistribuiçãoio e ",subsetor: "Medicamentos" },
  {papel: "PFRM3",setor: "ComércDistribuiçãoio e ",subsetor: "Medicamentos" },
  {papel: "PNVL3",setor: "ComércDistribuiçãoio e ",subsetor: "Medicamentos" },
  {papel: "PNVL4",setor: "ComércDistribuiçãoio e ",subsetor: "Medicamentos" },
  {papel: "RADL3",setor: "ComércDistribuiçãoio e ",subsetor: "Medicamentos" },
//   {papel: "RAIA3",setor: "ComércDistribuiçãoio e ",subsetor: "Medicamentos" ,inativo: true},
//   { papel: "MMAQ3", setor: "Comércio", subsetor: "Material de Transporte" ,inativo: true},
//   { papel: "MMAQ4", setor: "Comércio", subsetor: "Material de Transporte" ,inativo: true},
  { papel: "WLMM3", setor: "Comércio", subsetor: "Material de Transporte" },
  { papel: "WLMM4", setor: "Comércio", subsetor: "Material de Transporte" },
//   {papel: "AUTM3",setor: "Material de Transporte",subsetor: "Material Rodoviário" ,inativo: true},
//   {papel: "DHBI4",setor: "Material de Transporte",subsetor: "Material Rodoviário" ,inativo: true},
//   {papel: "DHBI3",setor: "Material de Transporte",subsetor: "Material Rodoviário" ,inativo: true},
  {papel: "FRAS3",setor: "Material de Transporte",subsetor: "Material Rodoviário" },
//   {papel: "FRAS4",setor: "Material de Transporte",subsetor: "Material Rodoviário" ,inativo: true},
  {papel: "LEVE3",setor: "Material de Transporte",subsetor: "Material Rodoviário" },
//   {papel: "LEVE4",setor: "Material de Transporte",subsetor: "Material Rodoviário" ,inativo: true},
  {papel: "MWET3",setor: "Material de Transporte",subsetor: "Material Rodoviário" },
  {papel: "MWET4",setor: "Material de Transporte",subsetor: "Material Rodoviário" },
  {papel: "MYPK3",setor: "Material de Transporte",subsetor: "Material Rodoviário" },
//   {papel: "MYPK4",setor: "Material de Transporte",subsetor: "Material Rodoviário" ,inativo: true},
//   {papel: "OSAO4",setor: "Material de Transporte",subsetor: "Material Rodoviário" ,inativo: true},
  {papel: "PLAS3",setor: "Material de Transporte",subsetor: "Material Rodoviário" },
  {papel: "POMO3",setor: "Material de Transporte",subsetor: "Material Rodoviário" },
  {papel: "POMO4",setor: "Material de Transporte",subsetor: "Material Rodoviário" },
  {papel: "RAPT3",setor: "Material de Transporte",subsetor: "Material Rodoviário" },
  {papel: "RCSL4",setor: "Material de Transporte",subsetor: "Material Rodoviário" },
  {papel: "RAPT4",setor: "Material de Transporte",subsetor: "Material Rodoviário" },
  {papel: "RSUL4",setor: "Material de Transporte",subsetor: "Material Rodoviário" },
  {papel: "TUPY3",setor: "Material de Transporte",subsetor: "Material Rodoviário" },
//   {papel: "TUPY4",setor: "Material de Transporte",subsetor: "Material Rodoviário" ,inativo: true},
//   {papel: "CBMA3",setor: "Material de Transporte",subsetor: "Material Ferroviário" ,inativo: true},
//   {papel: "CBMA4",setor: "Material de Transporte",subsetor: "Material Ferroviário" ,inativo: true},
  {papel: "EMBR3",setor: "Material de Transporte",subsetor: "Material Aeronáutico" },
//   {papel: "CCHI3",setor: "Construção e Engenharia",subsetor: "Materiais de Construção" ,inativo: true},
//   {papel: "CCHI4",setor: "Construção e Engenharia",subsetor: "Materiais de Construção" ,inativo: true},
  {papel: "ETER3",setor: "Construção e Engenharia",subsetor: "Materiais de Construção" },
//   {papel: "ETER4",setor: "Construção e Engenharia",subsetor: "Materiais de Construção" ,inativo: true},
  {papel: "HAGA3",setor: "Construção e Engenharia",subsetor: "Materiais de Construção" },
  {papel: "HAGA4",setor: "Construção e Engenharia",subsetor: "Materiais de Construção" },
  {papel: "PTBL3",setor: "Construção e Engenharia",subsetor: "Materiais de Construção" },
//   {papel: "PTBL4",setor: "Construção e Engenharia",subsetor: "Materiais de Construção" ,inativo: true},
  {papel: "MAGG3",setor: "Materiais Diversos",subsetor: "Materiais Diversos" },
//   {papel: "MAGS3",setor: "Materiais Diversos",subsetor: "Materiais Diversos" ,inativo: true},
//   {papel: "PRVI3",setor: "Materiais Diversos",subsetor: "Materiais Diversos" ,inativo: true},
//   {papel: "TROR3",setor: "Materiais Diversos",subsetor: "Materiais Diversos" ,inativo: true},
//   {papel: "TROR4",setor: "Materiais Diversos",subsetor: "Materiais Diversos" ,inativo: true},
  { papel: "DTEX3", setor: "Madeira e Papel", subsetor: "Madeira" },
//   { papel: "DURA4", setor: "Madeira e Papel", subsetor: "Madeira" ,inativo: true},
//   { papel: "DURA3", setor: "Madeira e Papel", subsetor: "Madeira" ,inativo: true},
  { papel: "EUCA3", setor: "Madeira e Papel", subsetor: "Madeira" },
  { papel: "EUCA4", setor: "Madeira e Papel", subsetor: "Madeira" },
//   { papel: "LGLO4", setor: "Comércio", subsetor: "Livrarias e Papelarias" ,inativo: true},
//   { papel: "LCSA3", setor: "Alimentos", subsetor: "Laticínios" ,inativo: true},
//   { papel: "LCSA4", setor: "Alimentos", subsetor: "Laticínios" ,inativo: true},
//   { papel: "VGOR3", setor: "Alimentos", subsetor: "Laticínios" ,inativo: true},
//   { papel: "VGOR4", setor: "Alimentos", subsetor: "Laticínios" ,inativo: true},
//   { papel: "VIGR3", setor: "Alimentos", subsetor: "Laticínios" ,inativo: true},
//   { papel: "DOCA3", setor: "Mídia", subsetor: "Jornais. Livros e Revistas" ,inativo: true},
//   { papel: "DOCA4", setor: "Mídia", subsetor: "Jornais. Livros e Revistas" ,inativo: true},
  { papel: "SEDU3", setor: "Mídia", subsetor: "Jornais. Livros e Revistas" },
  { papel: "SLED4", setor: "Mídia", subsetor: "Jornais. Livros e Revistas" },
  { papel: "SLED3", setor: "Mídia", subsetor: "Jornais. Livros e Revistas" },
  {papel: "BBRK3",setor: "Construção e Engenharia",subsetor: "Intermediação Imobiliária" },
  {papel: "LPSB3",setor: "Construção e Engenharia",subsetor: "Intermediação Imobiliária" },
//   { papel: "CTWR3", setor: "Hoteis e Restaurantes", subsetor: "Hotelaria" ,inativo: true},
  { papel: "HOOT4", setor: "Hoteis e Restaurantes", subsetor: "Hotelaria" },
  {papel: "BAHI3",setor: "Holdings Diversificadas",subsetor: "Holdings Diversificadas" },
//   {papel: "BAHI4",setor: "Holdings Diversificadas",subsetor: "Holdings Diversificadas" ,inativo: true},
//   {papel: "BAHI5",setor: "Holdings Diversificadas",subsetor: "Holdings Diversificadas" ,inativo: true},
  {papel: "BRAP3",setor: "Holdings Diversificadas",subsetor: "Holdings Diversificadas" },
  {papel: "BRAP4",setor: "Holdings Diversificadas",subsetor: "Holdings Diversificadas" },
  {papel: "BTTL3",setor: "Holdings Diversificadas",subsetor: "Holdings Diversificadas" },
  {papel: "BTTL4",setor: "Holdings Diversificadas",subsetor: "Holdings Diversificadas" },
  {papel: "HBTS5",setor: "Holdings Diversificadas",subsetor: "Holdings Diversificadas" },
  {papel: "JBDU3",setor: "Holdings Diversificadas",subsetor: "Holdings Diversificadas" },
  {papel: "JBDU4",setor: "Holdings Diversificadas",subsetor: "Holdings Diversificadas" },
  {papel: "MOAR3",setor: "Holdings Diversificadas",subsetor: "Holdings Diversificadas" },
//   {papel: "SUZA4",setor: "Holdings Diversificadas",subsetor: "Holdings Diversificadas" ,inativo: true},
  {papel: "TRPN3",setor: "Holdings Diversificadas",subsetor: "Holdings Diversificadas" },
  {papel: "UGPA3",setor: "Holdings Diversificadas",subsetor: "Holdings Diversificadas" },
//   {papel: "UGPA4",setor: "Holdings Diversificadas",subsetor: "Holdings Diversificadas" ,inativo: true},
  { papel: "CEGR3", setor: "Gás", subsetor: "Gás" },
  { papel: "CGAS3", setor: "Gás", subsetor: "Gás" },
  { papel: "CGAS5", setor: "Gás", subsetor: "Gás" },
//   { papel: "CLAN3", setor: "Alimentos", subsetor: "Grãos e Derivados" ,inativo: true},
//   { papel: "CLAN4", setor: "Alimentos", subsetor: "Grãos e Derivados" ,inativo: true},
//   { papel: "GRNL4", setor: "Alimentos", subsetor: "Grãos e Derivados" ,inativo: true},
//   { papel: "LECO4", setor: "Alimentos", subsetor: "Grãos e Derivados" ,inativo: true},
//   { papel: "LECO3", setor: "Alimentos", subsetor: "Grãos e Derivados" ,inativo: true},
//   {papel: "BUET3",setor: "Tecidos. Vestuário e Calçados",subsetor: "Fios e Tecidos" ,inativo: true},
//   {papel: "BUET4",setor: "Tecidos. Vestuário e Calçados",subsetor: "Fios e Tecidos" ,inativo: true},
  {papel: "CEDO3",setor: "Tecidos. Vestuário e Calçados",subsetor: "Fios e Tecidos" },
  {papel: "CEDO4",setor: "Tecidos. Vestuário e Calçados",subsetor: "Fios e Tecidos" },
  {papel: "CTKA3",setor: "Tecidos. Vestuário e Calçados",subsetor: "Fios e Tecidos" },
  {papel: "CTNM3",setor: "Tecidos. Vestuário e Calçados",subsetor: "Fios e Tecidos" },
  {papel: "CTKA4",setor: "Tecidos. Vestuário e Calçados",subsetor: "Fios e Tecidos" },
  {papel: "CTSA4",setor: "Tecidos. Vestuário e Calçados",subsetor: "Fios e Tecidos" },
  {papel: "CTNM4",setor: "Tecidos. Vestuário e Calçados",subsetor: "Fios e Tecidos" },
//   {papel: "CTSA8",setor: "Tecidos. Vestuário e Calçados",subsetor: "Fios e Tecidos" ,inativo: true},
  {papel: "CTSA3",setor: "Tecidos. Vestuário e Calçados",subsetor: "Fios e Tecidos" },
  {papel: "DOHL3",setor: "Tecidos. Vestuário e Calçados",subsetor: "Fios e Tecidos" },
  {papel: "DOHL4",setor: "Tecidos. Vestuário e Calçados",subsetor: "Fios e Tecidos" },
  {papel: "ECPR3",setor: "Tecidos. Vestuário e Calçados",subsetor: "Fios e Tecidos" },
  {papel: "ECPR4",setor: "Tecidos. Vestuário e Calçados",subsetor: "Fios e Tecidos" },
//   {papel: "FGUI3",setor: "Tecidos. Vestuário e Calçados",subsetor: "Fios e Tecidos" ,inativo: true},
//   {papel: "FGUI4",setor: "Tecidos. Vestuário e Calçados",subsetor: "Fios e Tecidos" ,inativo: true},
//   {papel: "FTRX3",setor: "Tecidos. Vestuário e Calçados",subsetor: "Fios e Tecidos" ,inativo: true},
//   {papel: "FTRX4",setor: "Tecidos. Vestuário e Calçados",subsetor: "Fios e Tecidos" ,inativo: true},
  {papel: "PTNT3",setor: "Tecidos. Vestuário e Calçados",subsetor: "Fios e Tecidos" },
  {papel: "PTNT4",setor: "Tecidos. Vestuário e Calçados",subsetor: "Fios e Tecidos" },
//   {papel: "SCLO3",setor: "Tecidos. Vestuário e Calçados",subsetor: "Fios e Tecidos" ,inativo: true},
//   {papel: "SCLO4",setor: "Tecidos. Vestuário e Calçados",subsetor: "Fios e Tecidos" ,inativo: true},
  {papel: "SGPS3",setor: "Tecidos. Vestuário e Calçados",subsetor: "Fios e Tecidos" },
//   {papel: "SJOS4",setor: "Tecidos. Vestuário e Calçados",subsetor: "Fios e Tecidos" ,inativo: true},
//   {papel: "SJOS3",setor: "Tecidos. Vestuário e Calçados",subsetor: "Fios e Tecidos" ,inativo: true},
  {papel: "TEKA3",setor: "Tecidos. Vestuário e Calçados",subsetor: "Fios e Tecidos" },
  {papel: "TEKA4",setor: "Tecidos. Vestuário e Calçados",subsetor: "Fios e Tecidos" },
//   {papel: "TENE7",setor: "Tecidos. Vestuário e Calçados",subsetor: "Fios e Tecidos" ,inativo: true},
//   {papel: "TENE5",setor: "Tecidos. Vestuário e Calçados",subsetor: "Fios e Tecidos" ,inativo: true},
  {papel: "TXRX3",setor: "Tecidos. Vestuário e Calçados",subsetor: "Fios e Tecidos" },
  {papel: "TXRX4",setor: "Tecidos. Vestuário e Calçados",subsetor: "Fios e Tecidos" },
//   {papel: "VINE5",setor: "Tecidos. Vestuário e Calçados",subsetor: "Fios e Tecidos" ,inativo: true},
//   {papel: "VINE3",setor: "Tecidos. Vestuário e Calçados",subsetor: "Fios e Tecidos" ,inativo: true},
//   {papel: "WMBY3",setor: "Tecidos. Vestuário e Calçados",subsetor: "Fios e Tecidos" ,inativo: true},
//   { papel: "FFTL3", setor: "Químicos", subsetor: "Fertilizantes e Defensivos" ,inativo: true},
//   { papel: "FFTL4", setor: "Químicos", subsetor: "Fertilizantes e Defensivos" ,inativo: true},
  { papel: "FHER3", setor: "Químicos", subsetor: "Fertilizantes e Defensivos" },
//   { papel: "ILMD3", setor: "Químicos", subsetor: "Fertilizantes e Defensivos" ,inativo: true},
//   { papel: "ILMD4", setor: "Químicos", subsetor: "Fertilizantes e Defensivos" ,inativo: true},
  { papel: "NUTR3", setor: "Químicos", subsetor: "Fertilizantes e Defensivos" },
  {papel: "BRDT3",setor: "Petróleo. Gás e Biocombustiveis",subsetor: "Exploração e/ou Refino e Distribuição" },
  {papel: "DMMO3",setor: "Petróleo. Gás e Biocombustiveis",subsetor: "Exploração e/ou Refino e Distribuição" },
  {papel: "ENAT3",setor: "Petróleo. Gás e Biocombustiveis",subsetor: "Exploração e/ou Refino e Distribuição" },
  {papel: "OGXP3",setor: "Petróleo. Gás e Biocombustiveis",subsetor: "Exploração e/ou Refino e Distribuição" },
  {papel: "PETR3",setor: "Petróleo. Gás e Biocombustiveis",subsetor: "Exploração e/ou Refino e Distribuição" },
  {papel: "PETR4",setor: "Petróleo. Gás e Biocombustiveis",subsetor: "Exploração e/ou Refino e Distribuição" },
  {papel: "PRIO3",setor: "Petróleo. Gás e Biocombustiveis",subsetor: "Exploração e/ou Refino e Distribuição" },
//   {papel: "RIPI3",setor: "Petróleo. Gás e Biocombustiveis",subsetor: "Exploração e/ou Refino e Distribuição" ,inativo: true},
//   {papel: "RIPI4",setor: "Petróleo. Gás e Biocombustiveis",subsetor: "Exploração e/ou Refino e Distribuição" ,inativo: true},
//   {papel: "RPMG4",setor: "Petróleo. Gás e Biocombustiveis",subsetor: "Exploração e/ou Refino e Distribuição" ,inativo: true},
  {papel: "RPMG3",setor: "Petróleo. Gás e Biocombustiveis",subsetor: "Exploração e/ou Refino e Distribuição" },
//   { papel: "ARTR3", setor: "Transporte", subsetor: "Exploração de Rodovias" ,inativo: true},
  { papel: "CCRO3", setor: "Transporte", subsetor: "Exploração de Rodovias" },
  { papel: "ECOR3", setor: "Transporte", subsetor: "Exploração de Rodovias" },
  { papel: "TPIS3", setor: "Transporte", subsetor: "Exploração de Rodovias" },
  {papel: "AHEB3",setor: "Exploração de Imóveis",subsetor: "Exploração de Imóveis" },
  {papel: "AGRO3",setor: "Exploração de Imóveis",subsetor: "Exploração de Imóveis" },
  {papel: "AHEB5",setor: "Exploração de Imóveis",subsetor: "Exploração de Imóveis" },
//   {papel: "AHEB6",setor: "Exploração de Imóveis",subsetor: "Exploração de Imóveis" ,inativo: true},
  {papel: "ALSC3",setor: "Exploração de Imóveis",subsetor: "Exploração de Imóveis" },
//   {papel: "BHGR3",setor: "Exploração de Imóveis",subsetor: "Exploração de Imóveis" ,inativo: true},
  {papel: "BRML3",setor: "Exploração de Imóveis",subsetor: "Exploração de Imóveis" },
  {papel: "BRPR3",setor: "Exploração de Imóveis",subsetor: "Exploração de Imóveis" },
  {papel: "CCPR3",setor: "Exploração de Imóveis",subsetor: "Exploração de Imóveis" },
//   {papel: "CORR3",setor: "Exploração de Imóveis",subsetor: "Exploração de Imóveis" ,inativo: true},
  {papel: "CORR4",setor: "Exploração de Imóveis",subsetor: "Exploração de Imóveis" },
  {papel: "GSHP3",setor: "Exploração de Imóveis",subsetor: "Exploração de Imóveis" },
  {papel: "IGTA3",setor: "Exploração de Imóveis",subsetor: "Exploração de Imóveis" },
//   {papel: "IVTT3",setor: "Exploração de Imóveis",subsetor: "Exploração de Imóveis" ,inativo: true},
  {papel: "LOGG3",setor: "Exploração de Imóveis",subsetor: "Exploração de Imóveis" },
  {papel: "MULT3",setor: "Exploração de Imóveis",subsetor: "Exploração de Imóveis" },
  {papel: "SCAR3",setor: "Exploração de Imóveis",subsetor: "Exploração de Imóveis" },
//   {papel: "SCAR4",setor: "Exploração de Imóveis",subsetor: "Exploração de Imóveis" ,inativo: true},
  {papel: "SSBR3",setor: "Exploração de Imóveis",subsetor: "Exploração de Imóveis" },
  {papel: "FRIO3",setor: "Equipamentos Elétricos",subsetor: "Equipamentos Elétricos" },
//   {papel: "RDTR3",setor: "Equipamentos Elétricos",subsetor: "Equipamentos Elétricos" ,inativo: true},
//   {papel: "TRFO3",setor: "Equipamentos Elétricos",subsetor: "Equipamentos Elétricos" ,inativo: true},
//   {papel: "TRFO4",setor: "Equipamentos Elétricos",subsetor: "Equipamentos Elétricos" ,inativo: true},
//   {papel: "SOND3",setor: "Construção e Engenharia",subsetor: "Engenharia Consultiva" ,inativo: true},
  {papel: "SOND5",setor: "Construção e Engenharia",subsetor: "Engenharia Consultiva" },
  {papel: "SOND6",setor: "Construção e Engenharia",subsetor: "Engenharia Consultiva" },
  {papel: "TCNO3",setor: "Construção e Engenharia",subsetor: "Engenharia Consultiva" },
  {papel: "TCNO4",setor: "Construção e Engenharia",subsetor: "Engenharia Consultiva" },
  { papel: "AELP3", setor: "Energia Elétrica", subsetor: "Energia Elétrica" },
//   { papel: "AESL3", setor: "Energia Elétrica", subsetor: "Energia Elétrica" ,inativo: true},
//   { papel: "AESL4", setor: "Energia Elétrica", subsetor: "Energia Elétrica" ,inativo: true},
  { papel: "AFLT3", setor: "Energia Elétrica", subsetor: "Energia Elétrica" },
//   { papel: "AFLU3", setor: "Energia Elétrica", subsetor: "Energia Elétrica" ,inativo: true},
//   { papel: "AFLU5", setor: "Energia Elétrica", subsetor: "Energia Elétrica" ,inativo: true},
  { papel: "ALUP3", setor: "Energia Elétrica", subsetor: "Energia Elétrica" },
  { papel: "ALUP4", setor: "Energia Elétrica", subsetor: "Energia Elétrica" },
//   { papel: "AMPI3", setor: "Energia Elétrica", subsetor: "Energia Elétrica" ,inativo: true},
  { papel: "CBEE3", setor: "Energia Elétrica", subsetor: "Energia Elétrica" },
  { papel: "CEBR3", setor: "Energia Elétrica", subsetor: "Energia Elétrica" },
  { papel: "CEBR6", setor: "Energia Elétrica", subsetor: "Energia Elétrica" },
  { papel: "CEBR5", setor: "Energia Elétrica", subsetor: "Energia Elétrica" },
  { papel: "CEEB3", setor: "Energia Elétrica", subsetor: "Energia Elétrica" },
  { papel: "CEED3", setor: "Energia Elétrica", subsetor: "Energia Elétrica" },
  { papel: "CEED4", setor: "Energia Elétrica", subsetor: "Energia Elétrica" },
  { papel: "CEEB5", setor: "Energia Elétrica", subsetor: "Energia Elétrica" },
  { papel: "CELP5", setor: "Energia Elétrica", subsetor: "Energia Elétrica" },
  { papel: "CELP7", setor: "Energia Elétrica", subsetor: "Energia Elétrica" },
  { papel: "CEPE5", setor: "Energia Elétrica", subsetor: "Energia Elétrica" },
//   { papel: "CEPE3", setor: "Energia Elétrica", subsetor: "Energia Elétrica" ,inativo: true},
  { papel: "CEPE6", setor: "Energia Elétrica", subsetor: "Energia Elétrica" },
  { papel: "CESP3", setor: "Energia Elétrica", subsetor: "Energia Elétrica" },
//   { papel: "CESP4", setor: "Energia Elétrica", subsetor: "Energia Elétrica" ,inativo: true},
  { papel: "CESP5", setor: "Energia Elétrica", subsetor: "Energia Elétrica" },
  { papel: "CESP6", setor: "Energia Elétrica", subsetor: "Energia Elétrica" },
//   { papel: "CGOS3", setor: "Energia Elétrica", subsetor: "Energia Elétrica" ,inativo: true},
//   { papel: "CGOS4", setor: "Energia Elétrica", subsetor: "Energia Elétrica" ,inativo: true},
  { papel: "CLSC3", setor: "Energia Elétrica", subsetor: "Energia Elétrica" },
  { papel: "CLSC4", setor: "Energia Elétrica", subsetor: "Energia Elétrica" },
//   { papel: "CLSC6", setor: "Energia Elétrica", subsetor: "Energia Elétrica" ,inativo: true},
//   { papel: "CLSC5", setor: "Energia Elétrica", subsetor: "Energia Elétrica" ,inativo: true},
  { papel: "CMIG3", setor: "Energia Elétrica", subsetor: "Energia Elétrica" },
  { papel: "CMIG4", setor: "Energia Elétrica", subsetor: "Energia Elétrica" },
  { papel: "COCE3", setor: "Energia Elétrica", subsetor: "Energia Elétrica" },
  { papel: "COCE5", setor: "Energia Elétrica", subsetor: "Energia Elétrica" },
//   { papel: "COCE6", setor: "Energia Elétrica", subsetor: "Energia Elétrica" ,inativo: true},
  { papel: "CPFE3", setor: "Energia Elétrica", subsetor: "Energia Elétrica" },
//   { papel: "CPFG3", setor: "Energia Elétrica", subsetor: "Energia Elétrica" ,inativo: true},
//   { papel: "CPFG4", setor: "Energia Elétrica", subsetor: "Energia Elétrica" ,inativo: true},
//   { papel: "CPFP4", setor: "Energia Elétrica", subsetor: "Energia Elétrica" ,inativo: true},
//   { papel: "CPLE5", setor: "Energia Elétrica", subsetor: "Energia Elétrica" ,inativo: true},
  { papel: "CPLE6", setor: "Energia Elétrica", subsetor: "Energia Elétrica" },
  { papel: "CPLE3", setor: "Energia Elétrica", subsetor: "Energia Elétrica" },
  { papel: "CPRE3", setor: "Energia Elétrica", subsetor: "Energia Elétrica" },
  { papel: "CSRN3", setor: "Energia Elétrica", subsetor: "Energia Elétrica" },
  { papel: "CSRN5", setor: "Energia Elétrica", subsetor: "Energia Elétrica" },
  { papel: "CSRN6", setor: "Energia Elétrica", subsetor: "Energia Elétrica" },
//   { papel: "EBEN4", setor: "Energia Elétrica", subsetor: "Energia Elétrica" ,inativo: true},
//   { papel: "ELCA4", setor: "Energia Elétrica", subsetor: "Energia Elétrica" ,inativo: true},
  { papel: "EGIE3", setor: "Energia Elétrica", subsetor: "Energia Elétrica" },
//   { papel: "ELCA3", setor: "Energia Elétrica", subsetor: "Energia Elétrica" ,inativo: true},
  { papel: "EKTR3", setor: "Energia Elétrica", subsetor: "Energia Elétrica" },
  { papel: "ELET5", setor: "Energia Elétrica", subsetor: "Energia Elétrica" },
  { papel: "ELET6", setor: "Energia Elétrica", subsetor: "Energia Elétrica" },
  { papel: "ELET3", setor: "Energia Elétrica", subsetor: "Energia Elétrica" },
//   { papel: "ELPL6", setor: "Energia Elétrica", subsetor: "Energia Elétrica" ,inativo: true},
//   { papel: "ELPL5", setor: "Energia Elétrica", subsetor: "Energia Elétrica" ,inativo: true},
  { papel: "EMAE4", setor: "Energia Elétrica", subsetor: "Energia Elétrica" },
  { papel: "EKTR4", setor: "Energia Elétrica", subsetor: "Energia Elétrica" },
//   { papel: "ELPL4", setor: "Energia Elétrica", subsetor: "Energia Elétrica" ,inativo: true},
  { papel: "ENBR3", setor: "Energia Elétrica", subsetor: "Energia Elétrica" },
//   { papel: "ENER3", setor: "Energia Elétrica", subsetor: "Energia Elétrica" ,inativo: true},
//   { papel: "ENER5", setor: "Energia Elétrica", subsetor: "Energia Elétrica" ,inativo: true},
//   { papel: "ENER6", setor: "Energia Elétrica", subsetor: "Energia Elétrica" ,inativo: true},
  { papel: "ENEV3", setor: "Energia Elétrica", subsetor: "Energia Elétrica" },
  { papel: "ENGI4", setor: "Energia Elétrica", subsetor: "Energia Elétrica" },
  { papel: "ENMT3", setor: "Energia Elétrica", subsetor: "Energia Elétrica" },
  { papel: "ENMT4", setor: "Energia Elétrica", subsetor: "Energia Elétrica" },
  { papel: "EQTL3", setor: "Energia Elétrica", subsetor: "Energia Elétrica" },
//   { papel: "ESCE3", setor: "Energia Elétrica", subsetor: "Energia Elétrica" ,inativo: true},
  { papel: "ELPL3", setor: "Energia Elétrica", subsetor: "Energia Elétrica" },
  { papel: "ENGI3", setor: "Energia Elétrica", subsetor: "Energia Elétrica" },
  { papel: "GEPA4", setor: "Energia Elétrica", subsetor: "Energia Elétrica" },
  { papel: "GEPA3", setor: "Energia Elétrica", subsetor: "Energia Elétrica" },
//   { papel: "GETI3", setor: "Energia Elétrica", subsetor: "Energia Elétrica" ,inativo: true},
//   { papel: "GETI4", setor: "Energia Elétrica", subsetor: "Energia Elétrica" ,inativo: true},
//   { papel: "IENG3", setor: "Energia Elétrica", subsetor: "Energia Elétrica" ,inativo: true},
//   { papel: "IENG5", setor: "Energia Elétrica", subsetor: "Energia Elétrica" ,inativo: true},
//   { papel: "LIGH3", setor: "Energia Elétrica", subsetor: "Energia Elétrica" ,inativo: true},
  { papel: "LIGT3", setor: "Energia Elétrica", subsetor: "Energia Elétrica" },
  { papel: "LIPR3", setor: "Energia Elétrica", subsetor: "Energia Elétrica" },
  { papel: "OMGE3", setor: "Energia Elétrica", subsetor: "Energia Elétrica" },
  { papel: "REDE3", setor: "Energia Elétrica", subsetor: "Energia Elétrica" },
//   { papel: "REDE4", setor: "Energia Elétrica", subsetor: "Energia Elétrica" ,inativo: true},
  { papel: "RNEW3", setor: "Energia Elétrica", subsetor: "Energia Elétrica" },
//   { papel: "RGEG3", setor: "Energia Elétrica", subsetor: "Energia Elétrica" ,inativo: true},
  { papel: "RNEW4", setor: "Energia Elétrica", subsetor: "Energia Elétrica" },
  { papel: "TAEE4", setor: "Energia Elétrica", subsetor: "Energia Elétrica" },
  { papel: "TAEE3", setor: "Energia Elétrica", subsetor: "Energia Elétrica" },
//   { papel: "TBLE5", setor: "Energia Elétrica", subsetor: "Energia Elétrica" ,inativo: true},
//   { papel: "TBLE6", setor: "Energia Elétrica", subsetor: "Energia Elétrica" ,inativo: true},
  { papel: "TIET3", setor: "Energia Elétrica", subsetor: "Energia Elétrica" },
  { papel: "TIET4", setor: "Energia Elétrica", subsetor: "Energia Elétrica" },
  { papel: "TRPL3", setor: "Energia Elétrica", subsetor: "Energia Elétrica" },
  { papel: "TRPL4", setor: "Energia Elétrica", subsetor: "Energia Elétrica" },
//   { papel: "DXTG4", setor: "Embalagens", subsetor: "Embalagens" ,inativo: true},
//   { papel: "MTIG3", setor: "Embalagens", subsetor: "Embalagens" ,inativo: true},
  { papel: "MTIG4", setor: "Embalagens", subsetor: "Embalagens" },
//   { papel: "PTPA3", setor: "Embalagens", subsetor: "Embalagens" ,inativo: true},
//   { papel: "PTPA4", setor: "Embalagens", subsetor: "Embalagens" ,inativo: true},
//   { papel: "REEM4", setor: "Embalagens", subsetor: "Embalagens" ,inativo: true},
//   {papel: "BMTO3",setor: "Utilidades Domésticas",subsetor: "Eletrodomésticos" ,inativo: true},
//   {papel: "BMTO4",setor: "Utilidades Domésticas",subsetor: "Eletrodomésticos" ,inativo: true},
//   { papel: "GLOB4", setor: "Comércio", subsetor: "Eletrodomésticos" ,inativo: true},
  {papel: "IGBR3",setor: "Utilidades Domésticas",subsetor: "Eletrodomésticos" },
//   {papel: "IGBR5",setor: "Utilidades Domésticas",subsetor: "Eletrodomésticos" ,inativo: true},
//   {papel: "IGBR6",setor: "Utilidades Domésticas",subsetor: "Eletrodomésticos" ,inativo: true},
  { papel: "MGLU3", setor: "Comércio", subsetor: "Eletrodomésticos" },
//   {papel: "MTBR3",setor: "Utilidades Domésticas",subsetor: "Eletrodomésticos" ,inativo: true},
//   {papel: "MTBR4",setor: "Utilidades Domésticas",subsetor: "Eletrodomésticos" ,inativo: true},
//   { papel: "SEMP3", setor: "Comércio", subsetor: "Eletrodomésticos" ,inativo: true},
  {papel: "SPRI3",setor: "Utilidades Domésticas",subsetor: "Eletrodomésticos" },
  {papel: "SPRI6",setor: "Utilidades Domésticas",subsetor: "Eletrodomésticos" },
  {papel: "SPRI5",setor: "Utilidades Domésticas",subsetor: "Eletrodomésticos" },
  { papel: "VVAR4", setor: "Comércio", subsetor: "Eletrodomésticos" },
  { papel: "VVAR3", setor: "Comércio", subsetor: "Eletrodomésticos" },
  {papel: "WHRL4",setor: "Utilidades Domésticas",subsetor: "Eletrodomésticos" },
  {papel: "WHRL3",setor: "Utilidades Domésticas",subsetor: "Eletrodomésticos" },
//   { papel: "AEDU3", setor: "Diversos", subsetor: "Educacional" ,inativo: true},
  { papel: "ANIM3", setor: "Diversos", subsetor: "Educacional" },
  { papel: "ESTC3", setor: "Diversos", subsetor: "Educacional" },
//   { papel: "ESTC4", setor: "Diversos", subsetor: "Educacional" ,inativo: true},
  { papel: "KROT3", setor: "Diversos", subsetor: "Educacional" },
//   { papel: "KROT4", setor: "Diversos", subsetor: "Educacional" ,inativo: true},
//   { papel: "SEBB3", setor: "Diversos", subsetor: "Educacional" ,inativo: true},
//   { papel: "SEBB4", setor: "Diversos", subsetor: "Educacional" ,inativo: true},
  { papel: "SEER3", setor: "Diversos", subsetor: "Educacional" },
//   {papel: "DPPI4",setor: "Petróleo. Gás e Biocombustiveis",subseDistribuiçãotor: " de Combustíveis" ,inativo: true},
//   {papel: "DPPI3",setor: "Petróleo. Gás e Biocombustiveis",subseDistribuiçãotor: " de Combustíveis" ,inativo: true},
//   {papel: "PTIP3",setor: "Petróleo. Gás e Biocombustiveis",subseDistribuiçãotor: " de Combustíveis" ,inativo: true},
//   {papel: "PTIP4",setor: "Petróleo. Gás e Biocombustiveis",subseDistribuiçãotor: " de Combustíveis" ,inativo: true},
//   { papel: "ARLA3", setor: "Tecidos. Vestuário e Calçados", subsetor: "Couro" ,inativo: true},
//   { papel: "ARLA4", setor: "Tecidos. Vestuário e Calçados", subsetor: "Couro" ,inativo: true},
  {papel: "BRIN3",setor: "Previdência e Seguros",subsetor: "Corretoras de Seguros" },
  {papel: "WIZS3",setor: "Previdência e Seguros",subsetor: "Corretoras de Seguros" },
  {papel: "AZEV3",setor: "Construção e Engenharia",subsetor: "Construção Pesada" },
  {papel: "AZEV4",setor: "Construção e Engenharia",subsetor: "Construção Pesada" },
//   {papel: "LIXC3",setor: "Construção e Engenharia",subsetor: "Construção Pesada" ,inativo: true},
//   {papel: "LIXC4",setor: "Construção e Engenharia",subsetor: "Construção Pesada" ,inativo: true},
  {papel: "MEND5",setor: "Construção e Engenharia",subsetor: "Construção Pesada" },
  {papel: "MEND6",setor: "Construção e Engenharia",subsetor: "Construção Pesada" },
//   {papel: "SULT3",setor: "Construção e Engenharia",subsetor: "Construção Pesada" ,inativo: true},
//   {papel: "SULT4",setor: "Construção e Engenharia",subsetor: "Construção Pesada" ,inativo: true},
//   {papel: "ABYA3",setor: "Construção e Engenharia",subsetor: "Construção Civil" ,inativo: true},
//   {papel: "AGEI3",setor: "Construção e Engenharia",subsetor: "Construção Civil" ,inativo: true},
//   {papel: "AGIN3",setor: "Construção e Engenharia",subsetor: "Construção Civil" ,inativo: true},
//   {papel: "BISA3",setor: "Construção e Engenharia",subsetor: "Construção Civil" ,inativo: true},
  {papel: "CALI4",setor: "Construção e Engenharia",subsetor: "Construção Civil" },
  {papel: "CALI3",setor: "Construção e Engenharia",subsetor: "Construção Civil" },
//   {papel: "CCIM3",setor: "Construção e Engenharia",subsetor: "Construção Civil" ,inativo: true},
//   {papel: "CPNY3",setor: "Construção e Engenharia",subsetor: "Construção Civil" ,inativo: true},
  {papel: "CRDE3",setor: "Construção e Engenharia",subsetor: "Construção Civil" },
  {papel: "CYRE3",setor: "Construção e Engenharia",subsetor: "Construção Civil" },
//   {papel: "CYRE4",setor: "Construção e Engenharia",subsetor: "Construção Civil" ,inativo: true},
  {papel: "DIRR3",setor: "Construção e Engenharia",subsetor: "Construção Civil" },
  {papel: "EZTC3",setor: "Construção e Engenharia",subsetor: "Construção Civil" },
  {papel: "EVEN3",setor: "Construção e Engenharia",subsetor: "Construção Civil" },
//   {papel: "GAFP3",setor: "Construção e Engenharia",subsetor: "Construção Civil" ,inativo: true},
//   {papel: "GAFP4",setor: "Construção e Engenharia",subsetor: "Construção Civil" ,inativo: true},
  {papel: "GFSA3",setor: "Construção e Engenharia",subsetor: "Construção Civil" },
  {papel: "HBOR3",setor: "Construção e Engenharia",subsetor: "Construção Civil" },
//   {papel: "INHA3",setor: "Construção e Engenharia",subsetor: "Construção Civil" ,inativo: true},
  {papel: "JFEN3",setor: "Construção e Engenharia",subsetor: "Construção Civil" },
  {papel: "JHSF3",setor: "Construção e Engenharia",subsetor: "Construção Civil" },
//   {papel: "KSSA3",setor: "Construção e Engenharia",subsetor: "Construção Civil" ,inativo: true},
  {papel: "MILS3",setor: "Construção e Engenharia",subsetor: "Construção Civil" },
  {papel: "MRVE3",setor: "Construção e Engenharia",subsetor: "Construção Civil" },
  {papel: "PDGR3",setor: "Construção e Engenharia",subsetor: "Construção Civil" },
  {papel: "RDNI3",setor: "Construção e Engenharia",subsetor: "Construção Civil" },
  {papel: "RSID3",setor: "Construção e Engenharia",subsetor: "Construção Civil" },
//   {papel: "SGEN3",setor: "Construção e Engenharia",subsetor: "Construção Civil" ,inativo: true},
//   {papel: "SGEN4",setor: "Construção e Engenharia",subsetor: "Construção Civil" ,inativo: true},
  {papel: "TCSA3",setor: "Construção e Engenharia",subsetor: "Construção Civil" },
  {papel: "TEND3",setor: "Construção e Engenharia",subsetor: "Construção Civil" },
  {papel: "TRIS3",setor: "Construção e Engenharia",subsetor: "Construção Civil" },
  {papel: "VIVR3",setor: "Construção e Engenharia",subsetor: "Construção Civil" },
//   {papel: "BEMA3",setor: "Computadores e Equipamentos",subsetor: "Computadores e Equipamentos" ,inativo: true},
  {papel: "ITEC3",setor: "Computadores e Equipamentos",subsetor: "Computadores e Equipamentos" },
  {papel: "POSI3",setor: "Computadores e Equipamentos",subsetor: "Computadores e Equipamentos" },
//   { papel: "CRUZ3", setor: "Fumo", subsetor: "Cigarros e Fumo" ,inativo: true},
  { papel: "ABEV3", setor: "Bebidas", subsetor: "Cervejas e Refrigerantes" },
//   { papel: "AMBV3", setor: "Bebidas", subsetor: "Cervejas e Refrigerantes" ,inativo: true},
//   { papel: "AMBV4", setor: "Bebidas", subsetor: "Cervejas e Refrigerantes" ,inativo: true},
  { papel: "BAUH4", setor: "Alimentos", subsetor: "Carnes e Derivados" },
  { papel: "BEEF3", setor: "Alimentos", subsetor: "Carnes e Derivados" },
  { papel: "BRFS3", setor: "Alimentos", subsetor: "Carnes e Derivados" },
//   { papel: "ELEV3", setor: "Alimentos", subsetor: "Carnes e Derivados" ,inativo: true},
  { papel: "JBSS3", setor: "Alimentos", subsetor: "Carnes e Derivados" },
  { papel: "MNPR3", setor: "Alimentos", subsetor: "Carnes e Derivados" },
//   { papel: "MNPR4", setor: "Alimentos", subsetor: "Carnes e Derivados" ,inativo: true},
  { papel: "MRFG3", setor: "Alimentos", subsetor: "Carnes e Derivados" },
//   { papel: "PRGA4", setor: "Alimentos", subsetor: "Carnes e Derivados" ,inativo: true},
//   { papel: "SDIA3", setor: "Alimentos", subsetor: "Carnes e Derivados" ,inativo: true},
//   { papel: "SDIA4", setor: "Alimentos", subsetor: "Carnes e Derivados" ,inativo: true},
  {papel: "ALPA3",setor: "Tecidos. Vestuário e Calçados",subsetor: "Calçados" },
  {papel: "ALPA4",setor: "Tecidos. Vestuário e Calçados",subsetor: "Calçados" },
//   {papel: "CAMB3",setor: "Tecidos. Vestuário e Calçados",subsetor: "Calçados" ,inativo: true},
  {papel: "CAMB4",setor: "Tecidos. Vestuário e Calçados",subsetor: "Calçados" },
  {papel: "GRND3",setor: "Tecidos. Vestuário e Calçados",subsetor: "Calçados" },
  {papel: "VULC3",setor: "Tecidos. Vestuário e Calçados",subsetor: "Calçados" },
//   {papel: "VULC4",setor: "Tecidos. Vestuário e Calçados",subsetor: "Calçados" ,inativo: true},
//   { papel: "CAFE3", setor: "Alimentos", subsetor: "Café" ,inativo: true},
//   { papel: "CAFE4", setor: "Alimentos", subsetor: "Café" ,inativo: true},
//   { papel: "CIQU3", setor: "Alimentos", subsetor: "Café" ,inativo: true},
//   { papel: "CIQU4", setor: "Alimentos", subsetor: "Café" ,inativo: true},
//   { papel: "IGUA3", setor: "Alimentos", subsetor: "Café" ,inativo: true},
//   { papel: "IGUA5", setor: "Alimentos", subsetor: "Café" ,inativo: true},
//   { papel: "IGUA6", setor: "Alimentos", subsetor: "Café" ,inativo: true},
  { papel: "ESTR3", setor: "Viagens e Lazer", subsetor: "Brinquedos e Jogos" },
  { papel: "ESTR4", setor: "Viagens e Lazer", subsetor: "Brinquedos e Jogos" },
  { papel: "TOYB3", setor: "Viagens e Lazer", subsetor: "Brinquedos e Jogos" },
  { papel: "TOYB4", setor: "Viagens e Lazer", subsetor: "Brinquedos e Jogos" },
//   { papel: "BCAL6", setor: "Viagens e Lazer", subsetor: "Bicicletas" ,inativo: true},
  { papel: "BMKS3", setor: "Viagens e Lazer", subsetor: "Bicicletas" },
//   { papel: "PMET3", setor: "Viagens e Lazer", subsetor: "Bicicletas" ,inativo: true},
//   { papel: "PMET5", setor: "Viagens e Lazer", subsetor: "Bicicletas" ,inativo: true},
//   { papel: "PMET6", setor: "Viagens e Lazer", subsetor: "Bicicletas" ,inativo: true},
//   { papel: "ABCB3", setor: "Financeiros", subsetor: "Bancos" ,inativo: true},
  { papel: "ABCB4", setor: "Financeiros", subsetor: "Bancos" },
  { papel: "BAZA3", setor: "Financeiros", subsetor: "Bancos" },
  { papel: "BBAS3", setor: "Financeiros", subsetor: "Bancos" },
  { papel: "BBDC3", setor: "Financeiros", subsetor: "Bancos" },
  { papel: "BBDC4", setor: "Financeiros", subsetor: "Bancos" },
  { papel: "BEES3", setor: "Financeiros", subsetor: "Bancos" },
  { papel: "BEES4", setor: "Financeiros", subsetor: "Bancos" },
  { papel: "BGIP3", setor: "Financeiros", subsetor: "Bancos" },
  { papel: "BGIP4", setor: "Financeiros", subsetor: "Bancos" },
//   { papel: "BICB3", setor: "Financeiros", subsetor: "Bancos" ,inativo: true},
//   { papel: "BICB4", setor: "Financeiros", subsetor: "Bancos" ,inativo: true},
  { papel: "BIDI4", setor: "Financeiros", subsetor: "Bancos" },
  { papel: "BMEB3", setor: "Financeiros", subsetor: "Bancos" },
  { papel: "BMEB4", setor: "Financeiros", subsetor: "Bancos" },
  { papel: "BMIN3", setor: "Financeiros", subsetor: "Bancos" },
  { papel: "BMIN4", setor: "Financeiros", subsetor: "Bancos" },
//   { papel: "BNBR4", setor: "Financeiros", subsetor: "Bancos" ,inativo: true},
  { papel: "BNBR3", setor: "Financeiros", subsetor: "Bancos" },
//   { papel: "BNCA3", setor: "Financeiros", subsetor: "Bancos" ,inativo: true},
  { papel: "BPAC3", setor: "Financeiros", subsetor: "Bancos" },
  { papel: "BPAC5", setor: "Financeiros", subsetor: "Bancos" },
  { papel: "BPAN4", setor: "Financeiros", subsetor: "Bancos" },
  { papel: "BPAR3", setor: "Financeiros", subsetor: "Bancos" },
//   { papel: "BPIA3", setor: "Financeiros", subsetor: "Bancos" ,inativo: true},
//   { papel: "BPNM3", setor: "Financeiros", subsetor: "Bancos" ,inativo: true},
  { papel: "BRGE5", setor: "Financeiros", subsetor: "Bancos" },
  { papel: "BRGE3", setor: "Financeiros", subsetor: "Bancos" },
  { papel: "BRGE6", setor: "Financeiros", subsetor: "Bancos" },
  { papel: "BRGE7", setor: "Financeiros", subsetor: "Bancos" },
  { papel: "BRGE8", setor: "Financeiros", subsetor: "Bancos" },
  { papel: "BRIV3", setor: "Financeiros", subsetor: "Bancos" },
  { papel: "BRIV4", setor: "Financeiros", subsetor: "Bancos" },
  { papel: "BRSR3", setor: "Financeiros", subsetor: "Bancos" },
//   { papel: "BRSR4", setor: "Financeiros", subsetor: "Bancos" ,inativo: true},
  { papel: "BRSR5", setor: "Financeiros", subsetor: "Bancos" },
  { papel: "BRSR6", setor: "Financeiros", subsetor: "Bancos" },
//   { papel: "BSCT3", setor: "Financeiros", subsetor: "Bancos" ,inativo: true},
//   { papel: "BSCT6", setor: "Financeiros", subsetor: "Bancos" ,inativo: true},
//   { papel: "BSCT5", setor: "Financeiros", subsetor: "Bancos" ,inativo: true},
  { papel: "BSLI3", setor: "Financeiros", subsetor: "Bancos" },
  { papel: "BSLI4", setor: "Financeiros", subsetor: "Bancos" },
//   { papel: "CZRS3", setor: "Financeiros", subsetor: "Bancos" ,inativo: true},
//   { papel: "CZRS4", setor: "Financeiros", subsetor: "Bancos" ,inativo: true},
//   { papel: "DAYC3", setor: "Financeiros", subsetor: "Bancos" ,inativo: true},
//   { papel: "DAYC4", setor: "Financeiros", subsetor: "Bancos" ,inativo: true},
  { papel: "IDVL3", setor: "Financeiros", subsetor: "Bancos" },
  { papel: "IDVL4", setor: "Financeiros", subsetor: "Bancos" },
  { papel: "ITSA3", setor: "Financeiros", subsetor: "Bancos" },
  { papel: "ITSA4", setor: "Financeiros", subsetor: "Bancos" },
  { papel: "ITUB3", setor: "Financeiros", subsetor: "Bancos" },
  { papel: "ITUB4", setor: "Financeiros", subsetor: "Bancos" },
//   { papel: "PINE3", setor: "Financeiros", subsetor: "Bancos" ,inativo: true},
  { papel: "PINE4", setor: "Financeiros", subsetor: "Bancos" },
//   { papel: "PRBC4", setor: "Financeiros", subsetor: "Bancos" ,inativo: true},
//   { papel: "PRBC3", setor: "Financeiros", subsetor: "Bancos" ,inativo: true},
//   { papel: "RNPT3", setor: "Financeiros", subsetor: "Bancos" ,inativo: true},
//   { papel: "RNPT4", setor: "Financeiros", subsetor: "Bancos" ,inativo: true},
  { papel: "RPAD3", setor: "Financeiros", subsetor: "Bancos" },
  { papel: "RPAD5", setor: "Financeiros", subsetor: "Bancos" },
  { papel: "RPAD6", setor: "Financeiros", subsetor: "Bancos" },
  { papel: "SANB4", setor: "Financeiros", subsetor: "Bancos" },
  { papel: "SANB3", setor: "Financeiros", subsetor: "Bancos" },
//   { papel: "SFSA3", setor: "Financeiros", subsetor: "Bancos" ,inativo: true},
//   { papel: "SFSA4", setor: "Financeiros", subsetor: "Bancos" ,inativo: true},
//   { papel: "UBBR3", setor: "Financeiros", subsetor: "Bancos" ,inativo: true},
//   { papel: "UBBR4", setor: "Financeiros", subsetor: "Bancos" ,inativo: true},
  { papel: "BSEV3", setor: "Alimentos", subsetor: "Açucar e Alcool" },
  { papel: "CSAN3", setor: "Alimentos", subsetor: "Açucar e Alcool" },
//   { papel: "UCOP4", setor: "Alimentos", subsetor: "Açucar e Alcool" ,inativo: true},
//   {papel: "CNFB4",setor: "Siderurgia e Metalurgia",subsetor: "Artefatos de Ferro e Aço" ,inativo: true},
//   {papel: "DUQE4",setor: "Siderurgia e Metalurgia",subsetor: "Artefatos de Ferro e Aço" ,inativo: true},
//   {papel: "DUQE3",setor: "Siderurgia e Metalurgia",subsetor: "Artefatos de Ferro e Aço" ,inativo: true},
//   {papel: "FBMC3",setor: "Siderurgia e Metalurgia",subsetor: "Artefatos de Ferro e Aço" ,inativo: true},
  {papel: "FBMC4",setor: "Siderurgia e Metalurgia",subsetor: "Artefatos de Ferro e Aço" },
//   {papel: "LETO3",setor: "Siderurgia e Metalurgia",subsetor: "Artefatos de Ferro e Aço" ,inativo: true},
//   {papel: "LETO5",setor: "Siderurgia e Metalurgia",subsetor: "Artefatos de Ferro e Aço" ,inativo: true},
//   {papel: "MGEL3",setor: "Siderurgia e Metalurgia",subsetor: "Artefatos de Ferro e Aço" ,inativo: true},
  {papel: "MGEL4",setor: "Siderurgia e Metalurgia",subsetor: "Artefatos de Ferro e Aço" },
  {papel: "PATI3",setor: "Siderurgia e Metalurgia",subsetor: "Artefatos de Ferro e Aço" },
  {papel: "PATI4",setor: "Siderurgia e Metalurgia",subsetor: "Artefatos de Ferro e Aço" },
  {papel: "TKNO4",setor: "Siderurgia e Metalurgia",subsetor: "Artefatos de Ferro e Aço" },
//   {papel: "WISA3",setor: "Siderurgia e Metalurgia",subsetor: "Artefatos de Ferro e Aço" ,inativo: true},
//   {papel: "WISA4",setor: "Siderurgia e Metalurgia",subsetor: "Artefatos de Ferro e Aço" ,inativo: true},
//   {papel: "CRBM3",setor: "Siderurgia e Metalurgia",subsetor: "Artefatos de Cobre" ,inativo: true},
//   {papel: "CRBM7",setor: "Siderurgia e Metalurgia",subsetor: "Artefatos de Cobre" ,inativo: true},
//   {papel: "ELUM3",setor: "Siderurgia e Metalurgia",subsetor: "Artefatos de Cobre" ,inativo: true},
//   {papel: "ELUM4",setor: "Siderurgia e Metalurgia",subsetor: "Artefatos de Cobre" ,inativo: true},
//   {papel: "FCAP3",setor: "Siderurgia e Metalurgia",subsetor: "Artefatos de Cobre" ,inativo: true},
//   {papel: "FCAP4",setor: "Siderurgia e Metalurgia",subsetor: "Artefatos de Cobre" ,inativo: true},
  {papel: "PMAM3",setor: "Siderurgia e Metalurgia",subsetor: "Artefatos de Cobre" },
//   {papel: "PMAM4",setor: "Siderurgia e Metalurgia",subsetor: "Artefatos de Cobre" ,inativo: true},
  {papel: "FJTA3",setor: "Máquinas e Equipamentos",subsetor: "Armas e Muniçães" },
  {papel: "FJTA4",setor: "Máquinas e Equipamentos",subsetor: "Armas e Muniçães" },
  { papel: "LCAM3", setor: "Diversos", subsetor: "Aluguel de Carros" },
  { papel: "MOVI3", setor: "Diversos", subsetor: "Aluguel de Carros" },
  { papel: "RENT3", setor: "Diversos", subsetor: "Aluguel de Carros" },
  { papel: "CAML3", setor: "Alimentos", subsetor: "Alimentos Diversos" },
//   { papel: "CTPC3", setor: "Alimentos", subsetor: "Alimentos Diversos" ,inativo: true},
//   { papel: "CTPC4", setor: "Alimentos", subsetor: "Alimentos Diversos" ,inativo: true},
  { papel: "JOPA3", setor: "Alimentos", subsetor: "Alimentos Diversos" },
  { papel: "JOPA4", setor: "Alimentos", subsetor: "Alimentos Diversos" },
  { papel: "MDIA3", setor: "Alimentos", subsetor: "Alimentos Diversos" },
  { papel: "SMTO3", setor: "Alimentos", subsetor: "Alimentos Diversos" },
//   { papel: "TERI3", setor: "Alimentos", subsetor: "Alimentos Diversos" ,inativo: true},
  { papel: "CRFB3", setor: "ComércDistribuiçãoio e ", subsetor: "Alimentos" },
  { papel: "PCAR3", setor: "ComércDistribuiçãoio e ", subsetor: "Alimentos" },
  { papel: "PCAR4", setor: "ComércDistribuiçãoio e ", subsetor: "Alimentos" },
//   { papel: "PCAR5", setor: "ComércDistribuiçãoio e ", subsetor: "Alimentos" ,inativo: true},
  { papel: "FRTA3", setor: "Agropecuária", subsetor: "Agricultura" },
//   { papel: "RSIP4", setor: "Agropecuária", subsetor: "Agricultura" ,inativo: true},
//   { papel: "RSIP3", setor: "Agropecuária", subsetor: "Agricultura" ,inativo: true},
  { papel: "SLCE3", setor: "Agropecuária", subsetor: "Agricultura" },
  { papel: "TESA3", setor: "Agropecuária", subsetor: "Agricultura" },
//   {papel: "MNDL4",setor: "Tecidos. Vestuário e Calçados",subsetor: "Acessórios" ,inativo: true},
  {papel: "MNDL3",setor: "Tecidos. Vestuário e Calçados",subsetor: "Acessórios" },
  {papel: "TECN3",setor: "Tecidos. Vestuário e Calçados",subsetor: "Acessórios" }
  // { papel: "ALBA3", inativo: true },
  // { papel: "APTI4", inativo: true },
  // { papel: "ARCE3", inativo: true },
  // { papel: "ARPS3", inativo: true },
  // { papel: "ARPS4", inativo: true },
  // { papel: "ARTE4", inativo: true },
  // { papel: "ARTE3", inativo: true },
  // { papel: "ASSM3", inativo: true },
  // { papel: "ASSM4", inativo: true },
  // { papel: "ASTA4", inativo: true },
  // { papel: "BECE3", inativo: true },
  // { papel: "BECE4", inativo: true },
  // { papel: "BELG3", inativo: true },
  // { papel: "BELG4", inativo: true },
  // { papel: "BERG3", inativo: true },
  // { papel: "BESP3", inativo: true },
  // { papel: "BESP4", inativo: true },
  // { papel: "BFIT3", inativo: true },
  // { papel: "BFIT4", inativo: true },
  // { papel: "BSGR3", inativo: true },
  // { papel: "CCTU4", inativo: true },
  // { papel: "CFLU4", inativo: true },
  // { papel: "CMET4", inativo: true },
  // { papel: "CMMA4", inativo: true },
  // { papel: "CPSL3", inativo: true },
  // { papel: "CRTP3", inativo: true },
  // { papel: "CRTP5", inativo: true },
  // { papel: "CSPC3", inativo: true },
  // { papel: "CSPC4", inativo: true },
  // { papel: "CSTB3", inativo: true },
  // { papel: "CSTB4", inativo: true },
  // { papel: "DFVA3", inativo: true },
  // { papel: "DFVA4", inativo: true },
  // { papel: "DJON4", inativo: true },
  // { papel: "EBCO3", inativo: true },
  // { papel: "EBCO4", inativo: true },
  // { papel: "ECIS3", inativo: true },
  // { papel: "EEEL3", inativo: true },
  // { papel: "ECIS4", inativo: true },
  // { papel: "EEEL4", inativo: true },
  // { papel: "FBRA4", inativo: true },
  // { papel: "FLCL3", inativo: true },
  // { papel: "FLCL5", inativo: true },
  // { papel: "FLCL6", inativo: true },
  // { papel: "GALO3", inativo: true },
  // { papel: "GALO4", inativo: true },
  // { papel: "ICPI3", inativo: true },
  // { papel: "ILLS4", inativo: true },
  // { papel: "JFAB4", inativo: true },
  // { papel: "LATS3", inativo: true },
  // { papel: "MNSA3", inativo: true },
  // { papel: "MNSA4", inativo: true },
  // { papel: "MSAN3", inativo: true },
  // { papel: "MSAN4", inativo: true },
  // { papel: "PALF3", inativo: true },
  // { papel: "PALF5", inativo: true },
  // { papel: "PLDN4", inativo: true },
  // { papel: "PLTO5", inativo: true },
  // { papel: "PLTO6", inativo: true },
  // { papel: "POPR4", inativo: true },
  // { papel: "PORP4", inativo: true },
  // { papel: "PTQS4", inativo: true },
  // { papel: "REPA3", inativo: true },
  // { papel: "REPA4", inativo: true },
  // { papel: "RPSA4", inativo: true },
  // { papel: "SALM3", inativo: true },
  // { papel: "SALM4", inativo: true },
  // { papel: "SLCP3", inativo: true },
  // { papel: "SNSY5", inativo: true },
  // { papel: "SUBA3", inativo: true },
  // { papel: "TCOC3", inativo: true },
  // { papel: "TCOC4", inativo: true },
  // { papel: "TDBH3", inativo: true },
  // { papel: "TDBH4", inativo: true },
  // { papel: "TLCP3", inativo: true },
  // { papel: "TLCP4", inativo: true },
  // { papel: "TNEP3", inativo: true },
  // { papel: "TNEP4", inativo: true },
  // { papel: "TSEP3", inativo: true },
  // { papel: "TSEP4", inativo: true },
  // { papel: "VVAX3", inativo: true },
  // { papel: "VVAX4", inativo: true }
];
